"""Shared pytest harness: runs every shipped fixture case against the FastAPI templates.

Fixtures are read from fixtures/<provider>.json (generated by fixtures/generate.mjs). The clock is frozen at
the fixture's generated_at so timestamped cases (Stripe, Paddle) stay meaningful forever. Node is NOT needed.
"""
import importlib.util
import json
import sys
import time
from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

ROOT = Path(__file__).resolve().parents[2]
TEMPLATES = ROOT / "templates" / "fastapi"


def load_fixture(provider: str) -> dict:
    return json.loads((ROOT / "fixtures" / f"{provider}.json").read_text())


def fresh_client(provider: str) -> TestClient:
    """Import the template as a brand-new module (fresh dedupe state) and mount its router."""
    path = TEMPLATES / f"{provider}_webhook.py"
    name = f"_tpl_{provider}_{time.monotonic_ns()}"
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    app = FastAPI()
    app.include_router(mod.router)
    return TestClient(app)


@pytest.fixture
def frozen_clock(monkeypatch):
    def freeze(seconds: float):
        monkeypatch.setattr(time, "time", lambda: float(seconds))
    return freeze
